import { IFn2Path } from './CmnLib';
import { TextDocument, ExtensionContext, Range } from 'vscode';
export declare class CteScore {
    readonly curPrj: string;
    private static localExtensionResRoots;
    private static htmBaseSrc;
    static init(ctx: ExtensionContext): void;
    private static hCur2Me;
    constructor(curPrj: string);
    private hPath2Tokens;
    updScore(path: string, curPrj: string, aToken: string[]): void;
    private repWvUri;
    add_lay(_o: any): void;
    isSkipUpd(path: string): boolean;
    separation(path: string): void;
    combining(path: string): void;
    updLine(doc: TextDocument, rng: Range, txt: string, aToken: string[]): boolean;
    private hPath2Wv;
    private resolveCustomTextEditor;
    private static regFld;
    private updWv_db;
    private hBufWords;
    updWords(key: string, Words: Set<string>): void;
    private hPrj2hPath;
    updPath(hPath: IFn2Path): void;
    private token2html;
    private make_tr;
    private make_tds_tag;
    undefMacro(def_nm: string): void;
    defMacro(def_nm: string, hPrm: any): void;
    private static readonly alzTagArg;
    private static readonly EXTS_PIC;
    private hTag2Tds;
    private macro_nm;
    private MAX_COL;
    private hCn2Col;
    private make_tds;
}
