import { ExtensionContext } from 'vscode';
export declare class PrjFileProc {
    private readonly ctx;
    private readonly dir;
    readonly chgTitle: (title: string) => void;
    private readonly rp;
    private readonly curPlg;
    private readonly curPrj;
    private readonly lenCurPrj;
    private readonly curCrypt;
    private readonly fld_crypt_prj;
    private $isCryptMode;
    get isCryptMode(): boolean;
    private regNeedCrypt;
    private regFullCrypt;
    private regRepJson;
    private regForceCrypt;
    private readonly hExt2N;
    private readonly hPass;
    private readonly aFSW;
    private readonly fnDiff;
    private hDiff;
    constructor(ctx: ExtensionContext, dir: string, chgTitle: (title: string) => void);
    private ps;
    openPrjSetting(): void;
    dispose(): void;
    private crePrj;
    private chgPrj;
    private delPrj;
    private readonly aRepl;
    tglCryptMode(): void;
    private initCrypt;
    private chkAndEnc;
    private readonly LEN_CHKDIFF;
    private isDiff;
    private updDiffJson;
    private pbkdf2;
    private iv;
    private readonly LEN_ENC;
    private readonly regDir;
    private encrypter;
    private updPlugin;
    private rebuildTask;
    private updPathJson;
    private readonly regSprSheetImg;
    private get_hPathFn2Exts;
    private addPath;
}
