import { ExtensionContext, WorkspaceFolder } from 'vscode';
export declare class Project {
    private readonly ctx;
    private readonly wsFld;
    readonly chgTitle: (title: string) => void;
    private readonly codSpt;
    private readonly curPlg;
    private readonly curPrj;
    private readonly lenCurPrj;
    private readonly curCrypto;
    private static readonly fld_crypto_prj;
    static get fldnm_crypto_prj(): string;
    private $isCryptoMode;
    get isCryptoMode(): boolean;
    private readonly regNeedCrypto;
    private readonly regFullCrypto;
    private readonly regRepPathJson;
    private readonly hExt2N;
    private readonly regNeedHash;
    private readonly encry;
    private readonly aFSW;
    private readonly fnDiff;
    private hDiff;
    private readonly pathWs;
    constructor(ctx: ExtensionContext, wsFld: WorkspaceFolder, chgTitle: (title: string) => void);
    private readonly ps;
    openPrjSetting(): void;
    get title(): any;
    get version(): any;
    dispose(): void;
    private crePrj;
    private chgPrj;
    private delPrj;
    private initCrypto;
    private encIfNeeded;
    private updDiffJson;
    private readonly LEN_CHKDIFF;
    private isDiff;
    private readonly REG_SPATH2HFN;
    private readonly aRepl;
    tglCryptoMode(): void;
    private static readonly LEN_ENC;
    private readonly regDir;
    private encrypter;
    private readonly regPlgAddTag;
    private updPlugin;
    private initTask;
    finInitTask(): void;
    private hPathFn2Exts;
    private updPathJson;
    private readonly regSprSheetImg;
    private get_hPathFn2Exts;
    private addPath;
    private userFnTail;
    private readonly regPath;
    private searchPath;
}
