import { ExtensionContext, WorkspaceFolder, TaskProcessEndEvent, TreeItem, EventEmitter } from 'vscode';
export declare class Project {
    private readonly ctx;
    private readonly chkLastSNVer;
    private readonly wsFld;
    readonly aTiRoot: TreeItem[];
    private readonly emPrjTD;
    private readonly hOnEndTask;
    private readonly codSpt;
    private readonly curPlg;
    private readonly curPrj;
    private readonly lenCurPrj;
    private readonly curCrypto;
    private static readonly fld_crypto_prj;
    static get fldnm_crypto_prj(): string;
    private isCryptoMode;
    private readonly regNeedCrypto;
    private readonly regFullCrypto;
    private readonly regRepPathJson;
    private readonly hExt2N;
    private readonly regNeedHash;
    private readonly encry;
    private readonly aFSW;
    private readonly fnDiff;
    private hDiff;
    private readonly aTreeTmp;
    private static readonly idxDevSnUpd;
    private updLocalSNVer;
    private static readonly idxDevCrypto;
    private dspCryptoMode;
    private aTiFlat;
    enableButton(enable: boolean): void;
    private readonly pathWs;
    constructor(ctx: ExtensionContext, chkLastSNVer: () => void, wsFld: WorkspaceFolder, aTiRoot: TreeItem[], emPrjTD: EventEmitter<TreeItem | undefined>, hOnEndTask: {
        [nm: string]: (e: TaskProcessEndEvent) => void;
    });
    private readonly hPush2BtnEnable;
    private onClickTreeItemBtn;
    private onClickTreeItemBtn_sub;
    private hTaskExecution;
    private readonly ps;
    private openPrjSetting;
    get title(): any;
    get version(): any;
    dispose(): void;
    private crePrj;
    private chgPrj;
    private delPrj;
    private initCrypto;
    private encIfNeeded;
    private updDiffJson;
    private readonly LEN_CHKDIFF;
    private isDiff;
    private readonly REG_SPATH2HFN;
    private readonly aRepl;
    private tglCryptoMode;
    private static readonly LEN_ENC;
    private readonly regDir;
    private encrypter;
    private readonly regPlgAddTag;
    private updPlugin;
    private initTask;
    finInitTask(): void;
    private hPathFn2Exts;
    private updPathJson;
    private readonly regSprSheetImg;
    private get_hPathFn2Exts;
    private addPath;
    private userFnTail;
    private readonly regPath;
    private searchPath;
}
